name: compile for Windows
    
on: [push, release]

jobs:
  build-n-publish:
    name: build Windows TPP
    run-on: windows-latest

    steps:
    - uses: action/checkout@master
    - name: set up Python 3.9.6
      
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requirements.txt
    - name: build exe using pyinstaller
      run: |
        pyinstaller WinTools.py
        python compile.py