name: compile for Windows
    
on: [push, release]

jobs:
  build:
    name: build Windows TPP
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.9.6
      
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requirements.txt
    - name: build exe using pyinstaller
      run: |
        pyinstaller --onefile --icon=icon.ico WinTools.py
    - name: packaging file
      run: |
        python compile.py
    - name: uploading TPP file
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: ./src/WinTools.tpp
        asset_name: WinTool $tag.tpp
        tag: ${{ github.ref }}
        overwrite: true
